### ISSUE TITLE
Adding a start menu 

### ISSUE THREAD

**Issue by 007vedant** [opencodenitr/hephaestus#13]
- Add a menu to the game.
- with start game, options, and exit buttons
- options contain volume enable/disable

something on the lines of [this](https://i.ytimg.com/vi/zc8ac_qUXQY/maxresdefault.jpg)
with layout matching with the games.

**Comment by mocno123** [comment]
Can I work on this please?

**Comment by 007vedant** [comment]
**@mocno123 ** Glad to assign this issue to you.
Please don't forget to star the repo.

**Comment by 007vedant** [comment]
@mocno123 I've reviewed the changes and everything seems great. I'll do a few minor tweaks later. 
So I'll be closing this issue via PR #22 . Let's work on more features for the game.
Great Job 👍 👍

**Comment by 007vedant** [comment]
@mocno123. There are a few minor issues with the PR you made so please rectify it via the new issue #24. 
Please comment over there, so I could assign you the new issue.
