### ISSUE TITLE
Adding sounds

### ISSUE THREAD

**Issue by 007vedant** [opencodenitr/hephaestus#14]
Add suitable sounds to the game
- for lasers
- for collision
- start menu music

**Comment by ddrm86** [comment]
Please assign this issue to me.

**Comment by 007vedant** [comment]
**@ddrm86** I have already started development work for this issue. Please work on the issue of adding main menu if possible.
Thanks.

**Comment by 007vedant** [comment]
Added sound functionalities for present features via PR #17
