### ISSUE TITLE
Add images for animation

### ISSUE THREAD

**Issue by 007vedant** [opencodenitr/hephaestus#18]
Add edited images of the enemy ships which could then be queued in high fps for blast animation.
Space ships blast when a collision occurs with laser or player ship.

images of enemy space ships can be found [here](https://github.com/opencodenitr/hephaestus/tree/main/Star%20Wars%20Lite/assets).

**Comment by shinozaki1595** [comment]
Please assign this issue to me.

**Comment by 007vedant** [comment]
**@shinozaki1595** Glad to assign this issue to you. Don't forget to pull the changes as I've done a few modifications since the issue was opened.
