### ISSUE TITLE
Add high score functionality in game

### ISSUE THREAD

**Issue by 007vedant** [opencodenitr/hephaestus#21]
1. saving and displaying top 3 high-scores
2. displayed via a button in the main menu (under development
3. any suitable logic for calculating high scores can be used. (preferably an easy mathematical function with inputs as -
    1. number of enemy ships destroyed
    2. the number of waves survived.

**Comment by FukurouMakoto** [comment]
Could I take a crack at this?

**Comment by 007vedant** [comment]
@FukurouMakoto Glad to assign this issue to you. 👍

**Comment by 007vedant** [comment]
via #25
