### ISSUE TITLE
Add restart functionality in the middle of the game.

### ISSUE THREAD

**Issue by 007vedant** [opencodenitr/hephaestus#7]
Could be done by binding a suitable restart function to a specific key.

**Comment by PushpikaWan** [comment]
I would like to try this one. can u assign this to me please

**Comment by ddrm86** [comment]
Hi!
Please assign this to me, although I need to be able to run the game first ( #8 )

**Comment by 007vedant** [comment]
Hi **@ddrm86**, Glad to assign this issue to you. The game script can be run from main.py after installing the required dependencies.
